const LOGIN_WIDTH = 480;
const LOGIN_HEIGHT = 580;

const MIN_WIDTH = 1000;
const MIN_HEIGHT = 640;

const WIDTH = 1200;
const HEIGHT = 800;

export { LOGIN_WIDTH, LOGIN_HEIGHT, MIN_WIDTH, MIN_HEIGHT, WIDTH, HEIGHT };
